"""
高德 LBS 代理接口
================

- 路由前缀：`/api/lbs`
- 鉴权：除 `share` 外仅需登录；`share` 需 admin 角色（防滥用配额）
- 数据源：未配置 `AMAP_WEBSERVICE_KEY` → `backend/data/lbs_mock/`
         配置后 → 真实高德 Web 服务（统一 3s 超时）
- 响应头：`X-LBS-Source: mock` / `live`，方便前端 / E2E 识别

端点
----
GET  /geocode          地址 → 经纬度
GET  /regeocode        经纬度 → 地址
GET  /place/text       POI 关键字搜索
GET  /place/around     周边搜索
GET  /staticmap        静态图 URL 生成
POST /share            生成分享卡（仅 admin）
"""
from __future__ import annotations

import logging
from typing import Optional

from fastapi import APIRouter, Depends, Response
from pydantic import BaseModel, Field

from backend.db.models import User
from backend.security.deps import get_current_user, require_admin
from backend.services.amap_client import get_amap_client

log = logging.getLogger(__name__)
router = APIRouter()


# ==================== 请求 / 响应模型 ====================
class ShareMarker(BaseModel):
    """分享卡 marker。"""
    lng: float
    lat: float
    name: Optional[str] = None
    label: Optional[str] = None


class ShareIn(BaseModel):
    """POST /share 入参。"""
    title: str = Field(default="我的卫星地图", max_length=100)
    markers: list[ShareMarker] = Field(default_factory=list)


# ==================== 端点 ====================
@router.get("/geocode")
async def geocode(
    response: Response,
    address: str,
    current_user: User = Depends(get_current_user),  # noqa: ARG001
) -> dict:
    """正向地理编码：地址 → 经纬度。"""
    client = get_amap_client()
    data, source = await client.geocode(address)
    response.headers["X-LBS-Source"] = source
    return data


@router.get("/regeocode")
async def regeocode(
    response: Response,
    lng: float,
    lat: float,
    current_user: User = Depends(get_current_user),  # noqa: ARG001
) -> dict:
    """逆地理编码：经纬度 → 地址。"""
    client = get_amap_client()
    data, source = await client.regeocode(lng, lat)
    response.headers["X-LBS-Source"] = source
    return data


@router.get("/place/text")
async def place_text(
    response: Response,
    keywords: str,
    city: Optional[str] = None,
    offset: int = 20,
    current_user: User = Depends(get_current_user),  # noqa: ARG001
) -> dict:
    """POI 关键字搜索。"""
    client = get_amap_client()
    data, source = await client.place_text(keywords=keywords, city=city, offset=offset)
    response.headers["X-LBS-Source"] = source
    return data


@router.get("/place/around")
async def place_around(
    response: Response,
    lng: float,
    lat: float,
    radius: int = 1000,
    types: Optional[str] = None,
    current_user: User = Depends(get_current_user),  # noqa: ARG001
) -> dict:
    """周边搜索。"""
    client = get_amap_client()
    data, source = await client.place_around(lng=lng, lat=lat, radius=radius, types=types)
    response.headers["X-LBS-Source"] = source
    # mock 模式且 fixture 距离被重算 → 加 X-LBS-Mock-Reason 头方便 E2E 验证
    if source == "mock":
        mock_meta = data.get("_mock_meta") or {}
        if mock_meta.get("reason"):
            response.headers["X-LBS-Mock-Reason"] = str(mock_meta["reason"])
    return data


@router.get("/staticmap")
async def static_map(
    response: Response,
    lng: float,
    lat: float,
    zoom: int = 14,
    size: str = "400*400",
    current_user: User = Depends(get_current_user),  # noqa: ARG001
) -> dict:
    """生成静态图 URL（不下载图片，前端直接 `<img :src="url">`）。"""
    client = get_amap_client()
    data, source = await client.static_map(lng=lng, lat=lat, zoom=zoom, size=size)
    response.headers["X-LBS-Source"] = source
    return data


@router.post("/share")
async def share(
    response: Response,
    payload: ShareIn,
    current_user: User = Depends(require_admin),
) -> dict:
    """生成分享卡：仅 admin 可调（防配额滥用）。

    入参：title + markers 列表。
    返回：{url, qrcode_base64, title, markers}
    """
    client = get_amap_client()
    data, source = await client.share_map(
        title=payload.title,
        markers=[m.model_dump() for m in payload.markers],
    )
    response.headers["X-LBS-Source"] = source
    log.info("share card generated by admin id=%s title=%s source=%s",
             current_user.id, payload.title, source)
    return data
